import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useSelector } from "react-redux"
import CreatePostCard from '../components/CreatePostCard'
import Header from '../components/Header'
import TimeLine from '../components/TimeLine'
import { RootState } from "../redux/app/store"

const Home: NextPage = () => {
  const userName = useSelector((state: RootState) => state.username.value)

  return (
    <>
      <Head>
        <title>CodeLeap | Engineering Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <CreatePostCard />

      <TimeLine />
    </>
  )
}

export default Home
