import type { NextPage } from 'next'
import Head from 'next/head'
import { useDispatch } from "react-redux"
import CreatePostCard from '../components/CreatePostCard'
import Header from '../components/Header'
import Feed from '../components/Feed'
import getPosts from '../actions/getPosts'
import { setPostList } from '../redux/app/slices/postListSlice'

export async function getServerSideProps() {
  const initialPostList = getPosts().then((res) => {
    return res
  })
  return {
    props: initialPostList
  }
}

const Home: NextPage = (props: any) => {
  const data = props.results
  const dispatch = useDispatch()

  dispatch(setPostList(data))

  return (
    <>
      <Head>
        <title>CodeLeap | Engineering Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <CreatePostCard />

      <Feed />
    </>
  )
}

export default Home
